---
title: "Data Science Project"
author: "Gege Gui"
date: "9/11/2017"
output: pdf_document
---

# Introduction:

PLOS (Public Library of Science) is a nonprofit Open Access publisher, innovator and advocacy organization with a mission to accelerate progress in science and medicine by leading a transformation in research communication. The data analysis project is to find out the most common statistical techniques in all published PLOS papers and the trends over the last 10-15 years.

# Data:

Follow the documentation from PLOS API website <http://api.plos.org/solr/examples/> to download statistics-related paper. Change pdf files to txt files, extract key words and publishing time from each paper. List common statistics techniques using several textbooks. (or from all key words)

# Related paper

Topics over Time: A Non-Markov Continuous-Time Model of Topical Trends

```{r}
library("rplos")
# Get only full article DOIs
id = searchplos(q="statistics", fl='id, publication_date', fq='doc_type:full', sort = 'publication_date desc', start=0)







Visualize word use across articles
plosword(list('monkey','Helianthus','sunflower','protein','whale'), vis = 'TRUE')
```